var menuContent2CircleId1 = document.getElementById("menu-content-2-circle-id1");
var menuContent2CircleId2 = document.getElementById("menu-content-2-circle-id2");
var menuContent2CircleId3 = document.getElementById("menu-content-2-circle-id3");
var menuContent2CircleId4 = document.getElementById("menu-content-2-circle-id4");
var menuContent2CircleId5 = document.getElementById("menu-content-2-circle-id5");
var menuContent2CircleId6 = document.getElementById("menu-content-2-circle-id6");
var contentMenuContent2Id1 = document.getElementById("content-menu-content-2-id1");
var contentMenuContent2Id2 = document.getElementById("content-menu-content-2-id2");
var contentMenuContent2Id3 = document.getElementById("content-menu-content-2-id3");
var contentMenuContent2Id4 = document.getElementById("content-menu-content-2-id4");
var contentMenuContent2Id5 = document.getElementById("content-menu-content-2-id5");
var contentMenuContent2Id6 = document.getElementById("content-menu-content-2-id6");
var menuContent2CircleId1Mobile = document.getElementById("menu-content-2-circle-id1-mobile");
var menuContent2CircleId2Mobile = document.getElementById("menu-content-2-circle-id2-mobile");
var menuContent2CircleId3Mobile = document.getElementById("menu-content-2-circle-id3-mobile");
var menuContent2CircleId4Mobile = document.getElementById("menu-content-2-circle-id4-mobile");
var menuContent2CircleId5Mobile = document.getElementById("menu-content-2-circle-id5-mobile");
var menuContent2CircleId6Mobile = document.getElementById("menu-content-2-circle-id6-mobile");

menuContent2CircleId1.onclick = function(){
	menuContent2CircleId1.style.background = '#9c5245';
	menuContent2CircleId2.style.background = 'white';
	menuContent2CircleId3.style.background = 'white';
	menuContent2CircleId4.style.background = 'white';
	menuContent2CircleId5.style.background = 'white';
	menuContent2CircleId6.style.background = 'white';
	contentMenuContent2Id1.style.display = 'flex';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId2.onclick = function(){
	menuContent2CircleId1.style.background = 'white';
	menuContent2CircleId2.style.background = '#9c5245';
	menuContent2CircleId3.style.background = 'white';
	menuContent2CircleId4.style.background = 'white';
	menuContent2CircleId5.style.background = 'white';
	menuContent2CircleId6.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'flex';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId3.onclick = function(){
	menuContent2CircleId1.style.background = 'white';
	menuContent2CircleId2.style.background = 'white';
	menuContent2CircleId3.style.background = '#9c5245';
	menuContent2CircleId4.style.background = 'white';
	menuContent2CircleId5.style.background = 'white';
	menuContent2CircleId6.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'flex';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId4.onclick = function(){
	menuContent2CircleId1.style.background = 'white';
	menuContent2CircleId2.style.background = 'white';
	menuContent2CircleId3.style.background = 'white';
	menuContent2CircleId4.style.background = '#9c5245';
	menuContent2CircleId5.style.background = 'white';
	menuContent2CircleId6.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'flex';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId5.onclick = function(){
	menuContent2CircleId1.style.background = 'white';
	menuContent2CircleId2.style.background = 'white';
	menuContent2CircleId3.style.background = 'white';
	menuContent2CircleId4.style.background = 'white';
	menuContent2CircleId5.style.background = '#9c5245';
	menuContent2CircleId6.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'flex';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId6.onclick = function(){
	menuContent2CircleId1.style.background = 'white';
	menuContent2CircleId2.style.background = 'white';
	menuContent2CircleId3.style.background = 'white';
	menuContent2CircleId4.style.background = 'white';
	menuContent2CircleId5.style.background = 'white';
	menuContent2CircleId6.style.background = '#9c5245';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'flex';
}
menuContent2CircleId1Mobile.onclick = function(){
	menuContent2CircleId1Mobile.style.background = '#9c5245';
	menuContent2CircleId2Mobile.style.background = 'white';
	menuContent2CircleId3Mobile.style.background = 'white';
	menuContent2CircleId4Mobile.style.background = 'white';
	menuContent2CircleId5Mobile.style.background = 'white';
	menuContent2CircleId6Mobile.style.background = 'white';
	contentMenuContent2Id1.style.display = 'flex';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId2Mobile.onclick = function(){
	menuContent2CircleId1Mobile.style.background = 'white';
	menuContent2CircleId2Mobile.style.background = '#9c5245';
	menuContent2CircleId3Mobile.style.background = 'white';
	menuContent2CircleId4Mobile.style.background = 'white';
	menuContent2CircleId5Mobile.style.background = 'white';
	menuContent2CircleId6Mobile.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'flex';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId3Mobile.onclick = function(){
	menuContent2CircleId1Mobile.style.background = 'white';
	menuContent2CircleId2Mobile.style.background = 'white';
	menuContent2CircleId3Mobile.style.background = '#9c5245';
	menuContent2CircleId4Mobile.style.background = 'white';
	menuContent2CircleId5Mobile.style.background = 'white';
	menuContent2CircleId6Mobile.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'flex';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId4Mobile.onclick = function(){
	menuContent2CircleId1Mobile.style.background = 'white';
	menuContent2CircleId2Mobile.style.background = 'white';
	menuContent2CircleId3Mobile.style.background = 'white';
	menuContent2CircleId4Mobile.style.background = '#9c5245';
	menuContent2CircleId5Mobile.style.background = 'white';
	menuContent2CircleId6Mobile.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'flex';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId5Mobile.onclick = function(){
	menuContent2CircleId1Mobile.style.background = 'white';
	menuContent2CircleId2Mobile.style.background = 'white';
	menuContent2CircleId3Mobile.style.background = 'white';
	menuContent2CircleId4Mobile.style.background = 'white';
	menuContent2CircleId5Mobile.style.background = '#9c5245';
	menuContent2CircleId6Mobile.style.background = 'white';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'flex';
	contentMenuContent2Id6.style.display = 'none';
}
menuContent2CircleId6Mobile.onclick = function(){
	menuContent2CircleId1Mobile.style.background = 'white';
	menuContent2CircleId2Mobile.style.background = '#white';
	menuContent2CircleId3Mobile.style.background = 'white';
	menuContent2CircleId4Mobile.style.background = 'white';
	menuContent2CircleId5Mobile.style.background = 'white';
	menuContent2CircleId6Mobile.style.background = '#9c5245';
	contentMenuContent2Id1.style.display = 'none';
	contentMenuContent2Id2.style.display = 'none';
	contentMenuContent2Id3.style.display = 'none';
	contentMenuContent2Id4.style.display = 'none';
	contentMenuContent2Id5.style.display = 'none';
	contentMenuContent2Id6.style.display = 'flex';
}